### ISSUE TITLE
fix-delay

### ISSUE THREAD

**Issue by akkaraponph** [lacakp/Project-Mask-Detection#5]
multi thread programming

**Comment by lacakp** [comment]
https://www.youtube.com/watch?v=lNyhMJlU83A

**Comment by lacakp** [comment]
https://www.pyimagesearch.com/2017/09/18/real-time-object-detection-with-deep-learning-and-opencv/

**Comment by lacakp** [comment]
https://www.youtube.com/watch?v=Z_uPIUbGCkA
